name: Build and release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup PNPM
      uses: pnpm/action-setup@v3
      with:
        version: 8
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        cache-dependency-path: pnpm-lock.yaml
    - name: Install dependencies
      run: pnpm install
    # - name: Set up git
    #   run: |
    #     git config user.name "github-action[bot]"
    #     git config user.email "samrichard@google.com"
    - name: Tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: minor
    - name: Get all tags
      uses: octokit/request-action@v2.x
      id: get_latest_release
      with:
        route: GET /repos/${{ github.repository }}/git/matching-refs/tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: pnpm bump && pnpm build
      env:
        KEY: ${{ secrets.KEY }}
        KEY_PASSPHRASE: ${{ secrets.KEY_PASSPHRASE }}
        VERSION: ${{ steps.tag_version.outputs.new_tag }}
        TAGS: ${{ steps.get_latest_release.outputs.data }}
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
        artifacts: './dist/iwa-sink.swbn,./update.json,./extension/IwaKitchenSinkExtension.crx,./extension/extension_manifest.xml'
